# Elisa: AI Learning Assistant
# © 2025 Dennis Schulmeister-Zimolong <dennis@wpvs.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

from pydantic    import BaseModel
from typing      import Any
from typing      import Literal

from .quiz.types import QuizActivity

ActivityData = QuizActivity
"""Combined data types of all supported activities"""

ActivityStatus = Literal["created", "running", "paused", "finished", "aborted"]
"""Current status of an activity """

class ActivityUpdate(BaseModel):
    """
    Updated value within the state dictionary of an activity.
    """
    path: list[str]
    """Deep path to traverse dicts and lists, e.g.: `["questions[0]", "text"]`"""

    value: Any
    """New value"""

class ActivityTransaction(BaseModel):
    """
    An update to an interactive activity, either generated by the client
    (usually after user interaction) of by the server.
    """
    id: str
    """Activity id"""

    status: ActivityStatus
    """New activity status"""

    updates: list[ActivityUpdate]
    """Updated values"""
